# Generated by Django 5.1 on 2025-05-25 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_lessontype_alter_schedule_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Без деления'), ('top', 'Числитель'), ('bottom', 'Знаменатель')], default='weekly', max_length=6, verbose_name='Тип недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.lessontype', verbose_name='Тип занятия'),
        ),
    ]
