# Generated by Django 5.1 on 2025-07-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_week_type_alter_schedule_lesson_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['start_time'], 'verbose_name': 'Время пары', 'verbose_name_plural': 'Время пар'},
        ),
    ]
