# Generated by Django 5.1 on 2025-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_alter_grade_user'),
        ('schedule', '0006_alter_lessontime_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='groups',
            field=models.ManyToManyField(to='academics.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Без деления'), ('top', 'Числитель'), ('bottom', 'Знаменатель')], default='weekly', max_length=7, verbose_name='Тип недели'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='group',
        ),
    ]
