# Generated by Django 5.1 on 2025-07-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_course_alter_group_course'),
        ('schedule', '0007_alter_schedule_unique_together_schedule_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
        ),
    ]
