# Generated by Django 5.1 on 2025-08-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_educationlevel'),
        ('schedule', '0008_alter_schedule_options_schedule_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='academics.educationlevel', verbose_name='Уровень образования'),
        ),
    ]
