# Generated by Django 5.1 on 2025-08-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_course_education_level_group_education_level_and_more'),
        ('schedule', '0009_schedule_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontime',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
    ]
