# Generated by Django 5.1 on 2025-09-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_remove_groupsubjectmentor_subjects_and_more'),
        ('schedule', '0010_lessontime_organization_room_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
    ]
