# Generated by Django 5.1 on 2025-09-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_schedule_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.lessontype', verbose_name='Тип занятия'),
        ),
    ]
