# Generated by Django 5.1 on 2025-01-01 18:05

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='achievements/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(related_name='users', to='account.achievement'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='account.rarity'),
        ),
    ]
