# Generated by Django 5.1 on 2025-01-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_group_alter_user_achievements_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
