# Generated by Django 5.1 on 2025-01-26 21:57

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_grade_grade'),
        ('account', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Инструмент')),
                ('logo', models.FileField(upload_to='programs/program-tools/', verbose_name='Лого инструмента')),
                ('description', models.CharField(max_length=255, verbose_name='Описание инструмента')),
            ],
            options={
                'verbose_name': 'Инструмент программы',
                'verbose_name_plural': 'Инструменты программы',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.achievement', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество достижений'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='academics.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='user_photos/%Y/%m', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор')], default='student', max_length=15, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.skill', verbose_name='Навыки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.tool', verbose_name='Инструменты'),
        ),
    ]
