# Generated by Django 5.1 on 2025-01-28 08:41

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='achievements/%Y/%m', verbose_name='Фото достижения'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='account.rarity', verbose_name='Редкость'),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название редкости'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
