# Generated by Django 5.1 on 2025-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль (открытый)'),
        ),
    ]
