# Generated by Django 5.1 on 2025-05-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_organization_group_organization_subject_organization'),
        ('account', '0014_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.organization', verbose_name='Учебное заведение'),
        ),
    ]
