# Generated by Django 5.1 on 2025-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_course_alter_group_course'),
        ('account', '0017_remove_user_education_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mentor_groups',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='academics.group', verbose_name='Группы ментора'),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_subjects',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='academics.subject', verbose_name='Предметы ментора'),
        ),
    ]
