# Generated by Django 5.1 on 2025-07-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_mentor_groups_user_mentor_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mentor_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentor_subjects',
        ),
    ]
