# Generated by Django 5.1 on 2025-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_user_mentor_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор'), ('scheduler', 'Составитель расписания')], default='student', max_length=15, verbose_name='Роль'),
        ),
    ]
