# Generated by Django 5.1 on 2025-08-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_course_education_level_group_education_level_and_more'),
        ('account', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.organization', verbose_name='Учебное заведение'),
        ),
    ]
