# Generated by Django 5.1 on 2025-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('mentor', 'Ментор'), ('scheduler', 'Составитель расписания'), ('admin', 'Админ')], default='student', max_length=15, verbose_name='Роль'),
        ),
    ]
