# Generated by Django 5.1 on 2025-09-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_remove_groupsubjectmentor_subjects_and_more'),
        ('account', '0024_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Если изменится пароль, то этот будет не действителен', max_length=20, null=True, verbose_name='Пароль (открытый)'),
        ),
    ]
