# Generated by Django 5.1 on 2025-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_user_organization_alter_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_meet_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Google Meet'),
        ),
    ]
