# Generated by Django 5.1 on 2025-09-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_alter_session_room'),
        ('account', '0026_user_google_meet_link'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='account_use_role_f4255b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='account_use_organiz_a211c0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='account_use_organiz_be5b24_idx'),
        ),
    ]
