# Generated by Django 5.1 on 2025-01-01 18:55

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rules', models.TextField(blank=True, help_text='Правила для группы', null=True)),
                ('contract', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='contracts/%Y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='subjects/%Y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.group')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
    ]
