# Generated by Django 5.1 on 2025-01-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
