# Generated by Django 5.1 on 2025-01-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_group_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-points']},
        ),
        migrations.AlterField(
            model_name='group',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
