# Generated by Django 5.1 on 2025-01-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Не был'), (1, 'Оценка 1'), (2, 'Оценка 2'), (3, 'Оценка 3'), (4, 'Оценка 4'), (5, 'Оценка 5')]),
        ),
    ]
