# Generated by Django 5.1 on 2025-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_grade_options_remove_grade_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', to='academics.subject'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
    ]
