# Generated by Django 5.1 on 2025-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_subject_unique_together_group_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Не был'), (10, 'Оценка 10'), (20, 'Оценка 20'), (30, 'Оценка 30'), (40, 'Оценка 40'), (50, 'Оценка 50'), (60, 'Оценка 60'), (70, 'Оценка 70'), (80, 'Оценка 80'), (90, 'Оценка 90'), (100, 'Оценка 100')]),
        ),
    ]
