# Generated by Django 5.1 on 2025-01-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(default='2020-05-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(choices=[(0, 'Не был'), (1, 'Оценка 1'), (2, 'Оценка 2'), (3, 'Оценка 3'), (4, 'Оценка 4'), (5, 'Оценка 5'), (6, 'Оценка 6'), (7, 'Оценка 7'), (8, 'Оценка 8'), (9, 'Оценка 9'), (10, 'Оценка 10')]),
        ),
    ]
