# Generated by Django 5.1 on 2025-05-22 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_group_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('start_time', models.TimeField(verbose_name='Начало занятия')),
                ('end_time', models.TimeField(verbose_name='Конец занятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session', verbose_name='Занятие'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user', 'session')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='date',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
    ]
