# Generated by Django 5.1 on 2025-07-30 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_groupsubjectmentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='groupsubjectmentor',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Наставник'),
        ),
    ]
