# Generated by Django 5.1 on 2025-08-08 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_group_curator_alter_groupsubjectmentor_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='make_up_file',
            field=models.FileField(blank=True, null=True, upload_to='makeup_submissions/%Y/%m', verbose_name='Файл отработки'),
        ),
        migrations.AddField(
            model_name='grade',
            name='make_up_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на отработку'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('canceled', 'Отменено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('payment_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('provider_payload', models.JSONField(blank=True, null=True, verbose_name='Ответ провайдера')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Время оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.grade', verbose_name='Оценка/занятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
