# Generated by Django 5.1 on 2025-08-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_grade_make_up_file_grade_make_up_link_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('success', 'Оплачено'), ('canceled', 'Отменено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, verbose_name='Токен провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_token', to='academics.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Платёжный токен организации',
                'verbose_name_plural': 'Платёжные токены организаций',
            },
        ),
    ]
