# Generated by Django 5.1 on 2025-08-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_lessontopic_session_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Уровень образования')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_levels', to='academics.organization', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
