# Generated by Django 5.1 on 2025-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_educationlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(default=1, upload_to='organizations/logos/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(default=1, max_length=255, verbose_name='Вебсайт'),
            preserve_default=False,
        ),
    ]
