# Generated by Django 5.1 on 2025-08-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_organization_logo_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.educationlevel', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='group',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='academics.educationlevel', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.educationlevel', verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
    ]
