# Generated by Django 5.1 on 2025-08-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_course_education_level_group_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='events_api',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='API для мероприятий'),
        ),
        migrations.AddField(
            model_name='organization',
            name='news_api',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='API для новостей'),
        ),
    ]
