# Generated by Django 5.1 on 2025-08-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_organization_events_api_organization_news_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.lessontopic', verbose_name='Тема урока'),
        ),
    ]
