# Generated by Django 5.1 on 2025-08-24 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_session_topic'),
        ('schedule', '0010_lessontime_organization_room_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='groups',
            field=models.ManyToManyField(to='academics.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='session',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Аудитория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('subject', 'teacher', 'room', 'date', 'start_time', 'end_time')},
        ),
    ]
