# Generated by Django 5.1 on 2025-08-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_alter_session_options_session_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('number', 'organization', 'education_level')},
        ),
    ]
