# Generated by Django 5.1 on 2025-09-04 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_alter_course_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubjectmentor',
            options={'verbose_name': 'Связка: группа–наставник', 'verbose_name_plural': 'Связки: группа–наставник'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='subjects',
        ),
        migrations.AlterUniqueTogether(
            name='groupsubjectmentor',
            unique_together={('group', 'mentor')},
        ),
        migrations.CreateModel(
            name='GroupSubjectMentorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_subject_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.groupsubjectmentor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'verbose_name': 'Предмет связки',
                'verbose_name_plural': 'Предметы связки',
                'unique_together': {('group_subject_mentor', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='groupsubjectmentor',
            name='subjects',
            field=models.ManyToManyField(related_name='group_subjects', through='academics.GroupSubjectMentorSubject', to='academics.subject', verbose_name='Предметы'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер семестра')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'ordering': ['course', 'number'],
                'unique_together': {('number', 'course')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester', verbose_name='Семестр'),
        ),
        migrations.RemoveField(
            model_name='groupsubjectmentor',
            name='subject',
        ),
    ]
