# Generated by Django 5.1 on 2025-09-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_alter_groupsubjectmentor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='group',
            name='rules',
        ),
    ]
