# Generated by Django 5.1 on 2025-09-04 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_remove_group_contract_remove_group_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubjectmentor',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.organization', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.session', verbose_name='Занятие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupsubjectmentorsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester', verbose_name='Семестр'),
            preserve_default=False,
        ),
    ]
