# Generated by Django 5.1 on 2025-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0033_remove_groupsubjectmentor_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsubjectmentor',
            name='subjects',
            field=models.ManyToManyField(related_name='mentor_links', through='academics.GroupSubjectMentorSubject', to='academics.subject', verbose_name='Предметы'),
        ),
    ]
