# Generated by Django 5.1 on 2025-09-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0034_groupsubjectmentor_subjects'),
        ('schedule', '0013_alter_schedule_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.room', verbose_name='Аудитория'),
        ),
    ]
