# Generated by Django 5.1 on 2025-09-14 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_alter_session_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsubjectmentorsubject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupsubjectmentorsubject',
            name='subject',
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.group', verbose_name='Группа')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Наставник')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Преподавание',
                'verbose_name_plural': 'Преподавания',
                'unique_together': {('mentor', 'group', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='GroupSubjectMentor',
        ),
        migrations.DeleteModel(
            name='GroupSubjectMentorSubject',
        ),
    ]
