# Generated by Django 5.1 on 2025-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0039_fix_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(0, 'Оценки нету'), (1, 'Оценка 1'), (2, 'Оценка 2'), (3, 'Оценка 3'), (4, 'Оценка 4'), (5, 'Оценка 5'), (6, 'Оценка 6'), (7, 'Оценка 7'), (8, 'Оценка 8'), (9, 'Оценка 9'), (10, 'Оценка 10')], null=True, verbose_name='Оценка'),
        ),
    ]
