# Generated by Django 5.1 on 2025-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='attendance',
            field=models.CharField(blank=True, choices=[('A', 'Присутствовал'), ('B', 'Отработка'), ('C', 'Опоздал')], max_length=1, null=True, verbose_name='Посещение'),
        ),
    ]
