# Generated by Django 5.1 on 2025-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_alter_grade_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=42.85889, max_digits=8, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=74.66778, max_digits=8, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='organization',
            name='radius_meters',
            field=models.PositiveIntegerField(default=100, verbose_name='Радиус допустимой зоны (м)'),
        ),
    ]
